# Generated by Django 6.0 on 2026-01-06 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=10, unique=True)),
                ('tracking_number', models.CharField(blank=True, max_length=25, null=True)),
                ('carrier', models.CharField(blank=True, choices=[('NZC', 'New Zealand Couriers'), ('P.Haste', 'Post Haste'), ('FWM', 'Mainfreight'), ('DHL', 'DHL')], max_length=25, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=25)),
                ('modified_by', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='shipment_photos')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(max_length=25)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='shipment_tracker.shipment')),
            ],
        ),
    ]
